# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Study/Subject_L/COD_LAB/LAB4/Screen/Screen.srcs/sources_1/ip/Rcolor_Mem/Rcolor_Mem.xci
# IP: The module: 'Rcolor_Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/Subject_L/COD_LAB/LAB4/Screen/Screen.srcs/sources_1/ip/Rcolor_Mem/Rcolor_Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rcolor_Mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Study/Subject_L/COD_LAB/LAB4/Screen/Screen.srcs/sources_1/ip/Rcolor_Mem/Rcolor_Mem.xci
# IP: The module: 'Rcolor_Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Study/Subject_L/COD_LAB/LAB4/Screen/Screen.srcs/sources_1/ip/Rcolor_Mem/Rcolor_Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rcolor_Mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
